### ISSUE TITLE
[Minor] Docker-compose up doesn't work out of the box

### ISSUE THREAD

**Issue by anthonygraignic** [ceramicnetwork/clayground#2]
Hi,
First of all, thanks for this nice sandbox environment config 👍  !

Just to let you know that the cmd `docker compose up` doesn't work after the git checkout.

I had to run `git submodule update --init --recursive` to fetch the submodules and be able to build & run the docker-compose.
Maybe it should be nice to fallback to public images from dockerhub if the subrepos folders are empty ? Or do you want to keep it that way ?

Note: the stacktrace for info:
```
anthony@DESKTOP:~/projects/workspace_test/clayground$ docker-compose up
Building ipfs

Traceback (most recent call last):
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 362, in ensure_image_exists
  File "compose/service.py", line 1147, in build
compose.service.BuildError: (<Service: ipfs>, {'message': 'Cannot locate specified Dockerfile: Dockerfile'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[376] Failed to execute script docker-compose
```

**Comment by oed** [comment]
Hey, thanks for reporting @anthonygraignic! This repo is indeed a bit out of date, we just haven't had time to update it yet. Feel free to submit a PR to update the submodules. 
As for your suggestion about using public images as fallback. How would that work? When would the fallback be triggered and when would it just use the submodules?

**Comment by anthonygraignic** [comment]
Hey back, 
Thanks for you answer, I started something https://github.com/anthonygraignic/clayground but have a problem with extending docker-compose files. I will wait for the CAS docker image release on Docker hub and main net launch to do a clean prod / dev docker-compose file.

As for my suggestion, I thought it was possible, but actually not. Using/pulling `image:` is the default behavior. So the best approach is to have an extended files with a `docker-compose.dev.yml` file where we `build` every image.

**Comment by oed** [comment]
Right, I guess it would be helpful to have two modes in this repo. One for running the latest releases from dockerhub and one for running the latest from the github repos (more aimed at devs building ceramic.

**Comment by v-stickykeys** [comment]
Hey @anthonygraignic you can now run everything from our docker images:

```sh
docker-compose up
```
In another shell
```sh
docker exec <container_id> packages/cli/bin/ceramic.js <command>
```

If it is useful at some point we'll also update a "developer" focused version that builds from submodules again.

**Comment by anthonygraignic** [comment]
Hey, thanks a lot @valmack , it's now working very smoothly !

Of course for the submodules, I don't think a lot of people will actually need it.
